services:
  gemini-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/home/appuser/app
      - ~/.gemini:/home/appuser/.gemini
      - ~/.config/gcloud:/home/appuser/.config/gcloud:ro
      - ~/.gitconfig:/home/appuser/.gitconfig:ro
    environment:
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT:-your-project-id}
    command: tail -f /dev/null
