services:
  gemini-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/appuser/${PROJECT_DIR_NAME}
      - .:/tmp:/tmp
      - ~/.gitconfig:/home/appuser/.gitconfig:ro
    environment:
      PROJECT_DIR_NAME: ${PROJECT_DIR_NAME}
    working_dir: /home/appuser/${PROJECT_DIR_NAME}
    command: tail -f /dev/null
